#include "ZME_Includes.h"

#pragma userclass (const = VARS)
// These variable are defined in CONST_VARS segment located at 0x0100
// If overflowed, make it bigger in UserClasses

// С учетом использования sigm'амского BOOTLOADER'а
// CONST_VARS(C:0x2000-C:0x27FF)
// Сегмент для смены частоты (0x2800-0x29FF)
// CODE(C:0x1800-C:0x19FF, C:0x3000-C:0xFFFB)
// CONST(C:0x1800-C:0x19FF, C:0x3000-C:0xFFFB)

#define CONST_CODE(var, val) BYTE const code var = val
CONST_CODE(_MANUFACTURER_ID_MAJOR, MANUFACTURER_ID_MAJOR);
CONST_CODE(_MANUFACTURER_ID_MINOR, MANUFACTURER_ID_MINOR);
CONST_CODE(_PRODUCT_TYPE_ID_MAJOR, PRODUCT_TYPE_ID_MAJOR);
CONST_CODE(_PRODUCT_TYPE_ID_MINOR, PRODUCT_TYPE_ID_MINOR);
CONST_CODE(_APP_VERSION_MAJOR_, PRODUCT_ID_MAJOR);
CONST_CODE(_APP_VERSION_MINOR_, PRODUCT_ID_MINOR);
CONST_CODE(_PRODUCT_FIRMWARE_VERSION_MAJOR, PRODUCT_FIRMWARE_VERSION_MAJOR);
CONST_CODE(_PRODUCT_FIRMWARE_VERSION_MINOR, PRODUCT_FIRMWARE_VERSION_MINOR);
CONST_CODE(_PRODUCT_GENERIC_TYPE,	PRODUCT_GENERIC_TYPE);
CONST_CODE(_PRODUCT_SPECIFIC_TYPE,	PRODUCT_SPECIFIC_TYPE);
#ifdef CUSTOM_CONST_CODE_PARAMETERS
CUSTOM_CONST_CODE_PARAMETERS


#if WITH_CC_WAKE_UP && WITH_CC_BATTERY
CONST_CODE(_DEFAULT_ENABLE_WAKEUPS, ENABLE_WAKEUPS_YES);
#endif

#endif

